[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/da-python/python-for-data-analytics/blob/main/Lesson5/numpy.ipynb)

# Numpy

In [ ]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])

In [3]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [4]:

y = np.array([[2,5],[1,1],[3,2]])

In [5]:
y

array([[2, 5],
       [1, 1],
       [3, 2]])

In [7]:
x.dot(y)

array([[14, 13],
       [12, 20]])

In [8]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [9]:
y

array([[2, 5],
       [1, 1],
       [3, 2]])

In [10]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(x)

numpy.ndarray

In [11]:
x.shape

(2, 3)

In [12]:
x.ndim

2

In [13]:
x.size

6

In [14]:
x.dtype

dtype('int64')

In [15]:
x.nbytes

48

In [16]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

In [17]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print(x)
print(x.nbytes)


[[1. 2. 3.]
 [4. 5. 6.]]
48


In [18]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(x)
print(x.nbytes)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [19]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.uint32)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
24


In [21]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(x.nbytes, "bytes")

48 bytes


In [23]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print( x.nbytes, "bytes")

24 bytes


In [24]:

x_copy = np.array(x, dtype=float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:

x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

# Операции с массивами

In [28]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [29]:
my_array

array([ 2, 14,  6,  8])

In [32]:
my_array + 2

array([ 4, 16,  8, 10])

In [33]:
my_array - 1

array([ 1, 13,  5,  7])

In [34]:
my_array * 2

array([ 4, 28, 12, 16])

In [35]:
my_array / 2

array([1., 7., 3., 4.])

In [36]:
second_array = np.zeros(4) + 3
second_array

array([3., 3., 3., 3.])

In [37]:
my_array

array([ 2, 14,  6,  8])

In [38]:
my_array - second_array


array([-1., 11.,  3.,  5.])

In [39]:

second_array / my_array

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [40]:
second_array = np.ones(4) + 3
second_array

array([4., 4., 4., 4.])

In [41]:

my_array - second_array


array([-2., 10.,  2.,  4.])

In [42]:

second_array / my_array

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [43]:

second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:

second_array = np.identity(4) + 3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [47]:
my_array

array([ 2, 14,  6,  8])

In [48]:
my_array - second_array

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [49]:
second_array / my_array

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [50]:

x = np.arange(3, 7, 0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [57]:
x = np.linspace(1.2, 40.5, num=100)
x

array([ 1.2       ,  1.5969697 ,  1.99393939,  2.39090909,  2.78787879,
        3.18484848,  3.58181818,  3.97878788,  4.37575758,  4.77272727,
        5.16969697,  5.56666667,  5.96363636,  6.36060606,  6.75757576,
        7.15454545,  7.55151515,  7.94848485,  8.34545455,  8.74242424,
        9.13939394,  9.53636364,  9.93333333, 10.33030303, 10.72727273,
       11.12424242, 11.52121212, 11.91818182, 12.31515152, 12.71212121,
       13.10909091, 13.50606061, 13.9030303 , 14.3       , 14.6969697 ,
       15.09393939, 15.49090909, 15.88787879, 16.28484848, 16.68181818,
       17.07878788, 17.47575758, 17.87272727, 18.26969697, 18.66666667,
       19.06363636, 19.46060606, 19.85757576, 20.25454545, 20.65151515,
       21.04848485, 21.44545455, 21.84242424, 22.23939394, 22.63636364,
       23.03333333, 23.43030303, 23.82727273, 24.22424242, 24.62121212,
       25.01818182, 25.41515152, 25.81212121, 26.20909091, 26.60606061,
       27.0030303 , 27.4       , 27.7969697 , 28.19393939, 28.59

In [62]:
np.geomspace(1, 625, num=5)



array([  1.,   5.,  25., 125., 625.])

In [64]:
np.logspace(3, 4, num=1000)

array([ 1000.        ,  1002.30754828,  1004.62042135,  1006.93863148,
        1009.26219099,  1011.59111222,  1013.92540756,  1016.26508939,
        1018.61017016,  1020.96066231,  1023.31657833,  1025.67793074,
        1028.04473209,  1030.41699495,  1032.79473192,  1035.17795563,
        1037.56667875,  1039.96091395,  1042.36067398,  1044.76597156,
        1047.17681949,  1049.59323056,  1052.01521762,  1054.44279353,
        1056.87597118,  1059.31476352,  1061.75918348,  1064.20924406,
        1066.66495828,  1069.12633917,  1071.59339982,  1074.06615333,
        1076.54461284,  1079.02879152,  1081.51870255,  1084.01435918,
        1086.51577465,  1089.02296226,  1091.53593533,  1094.05470721,
        1096.57929127,  1099.10970093,  1101.64594963,  1104.18805085,
        1106.7360181 ,  1109.2898649 ,  1111.84960482,  1114.41525147,
        1116.98681847,  1119.56431948,  1122.14776821,  1124.73717836,
        1127.33256371,  1129.93393803,  1132.54131515,  1135.15470892,
      

In [65]:
np.logspace(np.log10(3), np.log10(4), num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [51]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])

In [52]:
x == y


array([ True, False, False,  True])

In [68]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
np.array_equal(x, y)

True

In [53]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])
x < y

array([False,  True,  True, False])

In [54]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)

In [55]:
x

array([False,  True, False, False])

In [57]:
np.logical_or(x, y)

array([ True,  True, False,  True])

In [58]:
np.logical_and(x, y)

array([False,  True, False, False])

In [59]:
x = np.array([12, 16, 57, 11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [61]:
x = np.array([1, 2, 3, 4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [62]:

np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [63]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:

x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:

x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [67]:
x = np.arange(6).reshape(2, 3)

In [68]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:

x.T
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:

np.sum(x)

15

In [70]:

np.amin(x)

0

In [71]:

np.amax(x)

5

In [73]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [72]:

np.amin(x, axis=0)

array([0, 1, 2])

In [74]:

np.amin(x, axis=1)

array([0, 3])

In [75]:

np.percentile(x, 50)

2.5

In [76]:

x = np.array([1, -21, 3, -3])

In [77]:

np.argmax(x)

2

In [78]:

np.argmin(x)

1

In [79]:

x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [80]:

np.mean(x)

7.666666666666667

In [81]:

np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [82]:

np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [83]:
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [84]:

np.median(x)

4.5

In [85]:

np.std(x)

6.394442031083626

# Многомерные массивы

In [86]:
c = np.ones((4, 4))

In [87]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:

c * c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:

c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [91]:
y = np.arange(15).reshape(3, 5)
x = np.arange(10).reshape(2, 5)

In [92]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:

new_array = np.vstack((y, x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [94]:

y = np.arange(15).reshape(5, 3)
x = np.arange(10).reshape(5, 2)

In [95]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [96]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:

new_array = np.hstack((y, x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [98]:
from scipy import stats
x = np.random.rand(100, 10)

In [99]:
x

array([[2.41869705e-01, 6.12787012e-01, 8.92398890e-01, 5.38174026e-02,
        7.26957599e-01, 2.82355202e-01, 5.00156942e-01, 2.04141057e-01,
        3.43736131e-01, 8.10747669e-01],
       [8.47180578e-01, 6.10353289e-01, 7.76937181e-01, 3.06692599e-01,
        2.04979933e-01, 4.32978229e-01, 3.69298626e-01, 9.00247128e-01,
        9.48669130e-01, 1.88504348e-01],
       [2.99442587e-01, 4.05008729e-01, 6.05802097e-01, 5.15051615e-01,
        1.50179796e-01, 9.33270506e-01, 5.61625095e-01, 3.60083834e-01,
        1.81272738e-01, 9.22232427e-01],
       [6.94950907e-01, 9.79671183e-01, 8.98972508e-01, 4.47446057e-01,
        1.35499271e-01, 6.01132722e-03, 5.32707209e-01, 9.63787688e-02,
        3.23972864e-01, 6.94459196e-01],
       [1.65499051e-01, 5.95223224e-01, 2.70533142e-02, 2.54295765e-01,
        5.93103068e-01, 2.00551702e-01, 9.44156511e-01, 4.21292043e-01,
        4.50506936e-01, 5.19826928e-01],
       [4.47843758e-01, 2.94724638e-01, 2.44348280e-01, 8.37395355e-01,
   

In [100]:
stats.describe(x)

DescribeResult(nobs=100, minmax=(array([0.01268956, 0.00885921, 0.00365502, 0.00129953, 0.00063267,
       0.00230964, 0.01201035, 0.02487063, 0.0003597 , 0.0401139 ]), array([0.99824803, 0.99413403, 0.98368648, 0.97719619, 0.99007214,
       0.9963878 , 0.98326466, 0.9880556 , 0.98205004, 0.98210271])), mean=array([0.51776461, 0.44070921, 0.47842332, 0.48207282, 0.51039881,
       0.46962696, 0.49104787, 0.49664146, 0.45805627, 0.47838994]), variance=array([0.08664712, 0.06482455, 0.08411087, 0.08886046, 0.08104259,
       0.08725441, 0.07485139, 0.0889279 , 0.07792712, 0.07370221]), skewness=array([-0.03189613,  0.21564527,  0.12044021,  0.06840226,  0.05471477,
        0.09634387, -0.03010269, -0.01708921,  0.15151141,  0.15029937]), kurtosis=array([-1.22756245, -0.83169302, -1.23958065, -1.31506462, -1.18963822,
       -1.13789289, -1.06345723, -1.37047995, -1.20433546, -1.00322153]))

In [117]:
n, min_max, mean, var, skew, kurt = stats.describe(x)

In [118]:

new_array = np.vstack((mean, var, skew, kurt, min_max[0], min_max[1]))

In [119]:
new_array

array([[ 0.48723575,  0.54447702,  0.48103417,  0.47471681,  0.48570142,
         0.53180157,  0.50745501,  0.49295319,  0.4564022 ,  0.5019139 ],
       [ 0.06958548,  0.08012244,  0.08543527,  0.06591027,  0.08060761,
         0.08524676,  0.07750611,  0.08253985,  0.08019215,  0.09050178],
       [ 0.10035182, -0.20486787, -0.02586215,  0.06746891,  0.03701235,
        -0.04692468,  0.04563948,  0.06433147,  0.38121445, -0.11159432],
       [-1.22307875, -1.0867609 , -1.30735914, -0.91350133, -1.13222161,
        -1.23604514, -1.18087181, -1.14145096, -0.96584438, -1.38914117],
       [ 0.01105432,  0.00645654,  0.01107615,  0.0203442 ,  0.00321417,
         0.01725437,  0.00235816,  0.01454091,  0.01768677,  0.00608215],
       [ 0.98247619,  0.99900524,  0.95010891,  0.98244134,  0.99415778,
         0.99017118,  0.99823898,  0.99729526,  0.99506729,  0.97649225]])

In [120]:

new_array.T


array([[ 0.48723575,  0.06958548,  0.10035182, -1.22307875,  0.01105432,
         0.98247619],
       [ 0.54447702,  0.08012244, -0.20486787, -1.0867609 ,  0.00645654,
         0.99900524],
       [ 0.48103417,  0.08543527, -0.02586215, -1.30735914,  0.01107615,
         0.95010891],
       [ 0.47471681,  0.06591027,  0.06746891, -0.91350133,  0.0203442 ,
         0.98244134],
       [ 0.48570142,  0.08060761,  0.03701235, -1.13222161,  0.00321417,
         0.99415778],
       [ 0.53180157,  0.08524676, -0.04692468, -1.23604514,  0.01725437,
         0.99017118],
       [ 0.50745501,  0.07750611,  0.04563948, -1.18087181,  0.00235816,
         0.99823898],
       [ 0.49295319,  0.08253985,  0.06433147, -1.14145096,  0.01454091,
         0.99729526],
       [ 0.4564022 ,  0.08019215,  0.38121445, -0.96584438,  0.01768677,
         0.99506729],
       [ 0.5019139 ,  0.09050178, -0.11159432, -1.38914117,  0.00608215,
         0.97649225]])

# Индексы и слайсы

In [101]:
x = ["USA", "France", "Germany", "England"]
x[2]

'Germany'

In [102]:

x = ('USA', 3, "France", 4)
x[2]

'France'

In [103]:

x = np.arange(10)

In [104]:

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:

x[5]

5

In [106]:

x[-2]

8

In [129]:

x[2:8]

array([2, 3, 4, 5, 6, 7])

In [130]:

x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:

x[2:8:2]


array([2, 4, 6])

In [108]:

x = np.reshape(np.arange(16), (4, 4))

In [109]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:

x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:

x[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [111]:

x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [112]:

x = np.reshape(np.arange(16), (4, 4))

In [116]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:

x[[0, 1, 2], [0, 1, 3]]

array([ 0,  5, 11])

In [115]:

x = np.arange(16).reshape(4, 4)

In [141]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:

np.resize(x, (2, 2))

array([[0, 1],
       [2, 3]])

In [144]:

np.resize(x, (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:

x = np.arange(16).reshape(4, 4)

In [118]:

y = np.arange(6).reshape(2, 3)

In [119]:

x + y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [120]:

x = np.ones(16).reshape(4, 4)

In [123]:

y = np.arange(4)

In [124]:

x * y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [125]:

x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [126]:

y = np.arange(2).reshape(1, 2)
y

array([[0, 1]])

In [127]:

x * y

array([[0, 1],
       [0, 3]])